### ISSUE TITLE
Unhandled error in Deferred:

### ISSUE THREAD

**Issue by norhap** [OpenVisionE2/enigma2-openvision#29]
I have this error without being able to get the origin of the problem.
with ENIGMA_DEBUG_LVL=4 enigma2.
`Unhandled error in Deferred:`
Do you reproduce this?

**Comment by norhap** [comment]
I have located what causes it, it's up to me to fix this error in the background continuously every 3-5 seconds very annoying.

file mytest.py: lines 476-481

```
	from Components.SystemInfo import SystemInfo
	from enigma import getBoxType
	if SystemInfo["FirstCheckModel"] or SystemInfo["SecondCheckModel"] or SystemInfo["HiSilicon"] or SystemInfo["DifferentLCDSettings"] or getBoxType() in ("alphatriplehd","tmtwin4k","osminiplus","sf3038","spycat","et7x00","ebox5000","ebox7358","eboxlumi","ebox5000","maram9","sezam5000hd","mbtwin","sezam1000hd","mbmini","atemio5x00","beyonwizt3"):
		profile("VFDSYMBOLS")
		import Components.VfdSymbols
		Components.VfdSymbols.SymbolsCheck(session)
```

**Comment by norhap** [comment]
If errors occur, it is a sign that functionality has been broken

**Comment by persianpros** [comment]
What's your STB? Anyone else with this problem?

**Comment by norhap** [comment]
right now tested on "xpeedlx3" (OLED display) .... tomorrow I'll say results on two STB vuplus with VFD.
[https://ibb.co/ygHxMm2](url)

**Comment by atvcaptain** [comment]
enable twisted debug and fix the issue

**Comment by norhap** [comment]
thx atvcaptain
that's what I tried https://github.com/AbuBaniaz/enigma2-OpenATV/commit/c768f2ff5ddf1be953a5a617f5b64aba6c22af95
and it disappears ... but this brings another problem, we can not follow a hot log with ENIGMA_DEBUG_LVL=4 enigma2

it has the exit-log enigma2 but then this log is blocked and I can not follow it hot through the terminal.

**Comment by persianpros** [comment]
@Hains would you please check https://github.com/openatv/enigma2/commit/c768f2ff5ddf1be953a5a617f5b64aba6c22af95 and see if we could use it?

**Comment by norhap** [comment]
I've tried it with my git and your image, no problem works, but that code has a problem, we will not be able to get a level 4 enigma2 log hot, that code takes the whole log in hot to null.

**Comment by norhap** [comment]
the error disappears with https://github.com/norhap/enigma2-openvision/commit/92a05547f79b8cc040e83c905372c8108ea4a1dd

but I honestly do not know if the functions of that code are executed.

**Comment by persianpros** [comment]
I'm not sure either as I didn't see anyone uses that function like this.

**Comment by Hains** [comment]
To apply commit:
https://github.com/openatv/enigma2/commit/c768f2ff5ddf1be953a5a617f5b64aba6c22af95
to Open Vision, we have to use this patch

```
diff --git a/data/setup.xml b/data/setup.xml
index 60facf894..83750ef5d 100644
--- a/data/setup.xml
+++ b/data/setup.xml
@@ -91,6 +91,7 @@
 		<item level="2" text="Remember last service in PiP" description="Configure if and how long the latest service in the PiP will be remembered." requires="PIPAvailable">config.usage.pip_last_service_timeout</item>
 		<item level="2" text="Show VCR scart on main menu" description="When enabled, the VCR scart option will be shown on the main menu" requires="ScartSwitch">config.usage.show_vcr_scart</item>
 		<item level="2" text="Show True/False as graphical switch" description="Enable to display all true/false, yes/no, on/off and enable/disable set up options as a graphical switch.">config.usage.boolean_graphic</item>
+		<item level="2" text="Enable twisted log *" description="Allows you to enable the twisted log. They contain very detailed information of everything the twisted does.">config.misc.enabletwistedlog</item>
 	</setup>
 	<setup key="epgsettings" title="EPG settings">
 		<item level="2" text="Show EIT now/next in infobar" description="When enabled, display the EIT now/next eventdata in infobar. When disabled, display now/next eventdata from the EPG cache instead.">config.usage.show_eit_nownext</item>
diff --git a/mytest.py b/mytest.py
index fb1125beb..d02fdaa7c 100644
--- a/mytest.py
+++ b/mytest.py
@@ -103,6 +103,13 @@ except ImportError:
 
 profile("LOAD:Plugin")
 
+from twisted.python import log
+config.misc.enabletwistedlog = ConfigYesNo(default = False)
+if config.misc.enabletwistedlog.value == True:
+	log.startLogging(open('/tmp/twisted.log', 'w'))
+else:
+	log.startLogging(open('/dev/null', 'w'))
+
 # initialize autorun plugins and plugin menu entries
 from Components.PluginComponent import plugins
```
Since we don't have the old 'log.startLogging' code and we don't have a 'log settings' setup menu (yet?)
So i added it to 'User interface' submenu.
It's no problem, tested and no GSOD.

So i can add patch to Enigma2.

**Comment by persianpros** [comment]
I think first we need to be sure about "ENIGMA_DEBUG_LVL=4" to work as @norhap described it.

**Comment by norhap** [comment]
if first we must confirm that the whole record is not sent to dev/null  **('/dev/null', 'w'))**.... if this is so we will not be able to trace a live record .... twisted.log will receive the start of enigma2 (log output start enigma2 ) then it remains blocked since that code sends everything to dev / null, it also remains blocked live in the terminal.... we can not follow the work of enigma2 live.

that was my result when I tested that code.

**Comment by persianpros** [comment]
@norhap please test https://github.com/OpenVisionE2/enigma2-openvision/commit/8eb7ab679c27d9b66daa6edb5ca28ee35b03af87
