### ISSUE TITLE
ImportError: cannot import name ServiceReference

### ISSUE THREAD

**Issue by audi06** [OpenVisionE2/enigma2-openvision#42]
Hi @persianpros 

dm900 
version 9.3-r110
```
<    97.614>   File "/usr/lib/enigma2/python/mytest.py", line 41, in <module>
<    97.614>     from Screens import InfoBar
<    97.614>   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 16, in <module>
<    97.614>   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 2, in <module>
<    97.614>   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 14, in <module>
<    97.614>   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 15, in <module>
<    97.614>   File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 16, in <module>
<    97.615>   File "/usr/lib/enigma2/python/Screens/TimerEntry.py", line 23, in <module>
<    97.615>   File "/usr/lib/enigma2/python/Tools/FallbackTimer.py", line 2, in <module>
<    97.615> ImportError: cannot import name ServiceReference
```

**Comment by aouamed** [comment]
vuuno4kse  ov_9.3-r110 

  731.001>   File "/usr/lib/enigma2/python/mytest.py", line 41, in <module>
<   731.002>     from Screens import InfoBar
<   731.002>   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 16, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 2, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 14, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 15, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 16, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Screens/TimerEntry.py", line 23, in <module>
<   731.002>   File "/usr/lib/enigma2/python/Tools/FallbackTimer.py", line 2, in <module>
<   731.003> ImportError: cannot import name ServiceReference
<   731.004> [eDVBDB] ---- saving lame channel db
<   731.004> [eDVBDB] saved 0 channels and 0 services!
<   731.012> [eDVBResourceManager] release cached channel (timer timeout)
<   731.012> [Avahi] avahi_timeout_new
<   731.013> [Avahi] avahi_timeout_free
<   731.013> [Avahi] avahi_watch_free
<   731.013> [Avahi] avahi_timeout_free
<   731.014> [eInit] - (41) eServiceFactoryDVD
<   731.015> [eInit] - (41) eServiceFactoryWebTS
<   731.015> [eInit] - (41) eServiceFactoryTS
<   731.015> [eInit] - (41) eServiceFactoryHDMI
<   731.015> [eInit] - (41) eServiceFactoryM2TS
<   731.015> [eInit] - (41) eServiceFactoryFS
<   731.015> [eInit] - (41) eServiceFactoryDVB
<   731.015> [eInit] - (41) Encoders
<   731.015> [eInit] - (41) RTSP Stream server
<   731.016> [eInit] - (41) Stream server
<   731.016> [eInit] - (40) eServiceCenter
<   731.016> [eInit] - (35) CI Slots
<   731.016> [eInit] - (35) CA handler
<   731.016> [eInit] - (30) eActionMap
<   731.016> [eInit] - (22) Hdmi CEC driver
<   731.016> [eInit] - (21) input device driver
<   731.045> [eInit] - (20) DVB-CI UI
<   731.045> [eInit] - (20) UHF Modulator
<   731.045> [eInit] - (20) RC Input layer
<   731.045> [eInit] - (20) misc options
<   731.045> [eInit] - (20) AVSwitch Driver
<   731.045> [eInit] - (15) eWindowStyleManager
<   731.045> [eInit] - (10) gRC
<   731.045> [gRC] waiting for gRC thread shutdown
<   731.145> [gRC] thread has finished
<   731.145> [eInit] - (9) GFBDC
<   731.146> [eInit] - (9) gLCD
<   731.146> [eInit] - (9) Font Render Class
<   731.146> [eInit] - (8) graphics acceleration manager
<   731.146> [eInit] - (5) Tuxtxt
<   731.146> [eInit] - (1) Background File Eraser
<   731.146> [eInit] reached rl -1

**Comment by persianpros** [comment]
Thanks we about the problem and we're working on it.
