### ISSUE TITLE
image stuck at boot logo | vu solo 

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/enigma2-openvision#46]
here is the debug log :

<  1888.516> [Avahi] avahi_timeout_new
<  1888.516> [Avahi] avahi_watch_new(3 0x1)
<  1888.518> [Avahi] avahi_timeout_new
<  1888.523> [Avahi] avahi_timeout_free
<  1888.524> [Avahi] avahi_timeout_update
<  1888.526> [Avahi] avahi_timeout_new
<  1888.528> [Avahi] avahi_timeout_free
<  1888.530> [Avahi] avahi_timeout_new
<  1888.533> [Avahi] avahi_timeout_free
<  1888.534> [Avahi] avahi_timeout_new
<  1888.538> [Avahi] avahi_timeout_free
<  1888.539> [Avahi] avahi_timeout_new
<  1888.551> [Avahi] avahi_timeout_free
<  1888.553> [Avahi] avahi_timeout_new
<  1888.557> [Avahi] avahi_timeout_free
<  1888.558> [Avahi] client state: 2
<  1888.560> [Avahi] avahi_timeout_new
<  1888.567> [Avahi] avahi_timeout_free
<  1888.569> [eInit] + (1) Background File Eraser
<  1888.569> [eInit] + (5) Tuxtxt
<  1888.570> [eInit] + (8) graphics acceleration manager
<  1888.580> [eInit] + (9) GFBDC
<  1888.581> [fb] /dev/fb0: 21600k video mem
<  1888.582> [fb] 21600k video mem
<  1888.584> [fb] double buffering available!
<  1888.585> [fb] 2 page(s) available!
<  1888.639> [gFBDC] resolution: 720 x 576 x 32 (stride: 7680) pages: 2
<  1888.639> [gFBDC] 12960kB available for acceleration surfaces.
<  1888.640> [eInit] + (9) gLCD
<  1888.642> [eFbLCD] /dev/fb1: No such file or directory
<  1888.642> [eFbLCD] framebuffer /dev/fb1 not available
<  1888.652> [eLCD] xres=132, yres=64, bpp=8 lcd_type=1
<  1888.654> [eLCD] (132x64x8) buffer 0x822d88 8448 bytes, stride 132
<  1888.654> [gLCDDC] resolution: 132x64x8 stride=132
<  1888.655> [eInit] + (9) Font Render Class
<  1888.655> [Font] Initializing lib.
<  1888.657> [Font] Loading fonts.
<  1888.657> [Font] Intializing font cache, using max. 4MB.
<  1888.658> [eInit] + (10) gRC
<  1888.659> [gRC] thread created successfully
<  1888.660> [eInit] + (15) eWindowStyleManager
<  1888.660> [eInit] + (20) DVB-CI UI
<  1888.662> [eInit] + (20) UHF Modulator
<  1888.663> [eRFmod] couldnt open /dev/rfmod0: No such file or directory
<  1888.663> [eInit] + (20) RC Input layer
<  1888.664> [eInit] + (20) misc options
<  1888.665> [eInit] + (20) AVSwitch Driver
<  1888.667> [eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: No such file or directory
<  1888.668> [eInit] + (21) input device driver
<  1888.670> [eInputDeviceInit] adding device /dev/input/event0
<  1888.670> [eRCInputEventDriver] devicename=dreambox remote control (native)
<  1888.671> [eRCInputEventDriver] devicename=dreambox remote control (native)
<  1888.672> [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
<  1888.673> [eInputDeviceInit] Found 1 input devices.
<  1888.673> [eInit] + (22) Hdmi CEC driver
<  1888.674> [eHdmiCEC] detected physical address change: 1000 --> FFFF
<  1888.675> [eHdmiCEC] send message 84 FF FF 03
<  1888.678> [eInit] + (30) eActionMap
<  1888.678> [eInit] + (35) CI Slots
<  1888.679> [eServerSocket] ERROR on bind: No such file or directory
<  1888.681> [CI] scanning for common interfaces..
<  1888.693> [CI] Slot: 0 setSource: A
<  1888.694> [CI] Slot: 1 setSource: A
<  1888.722> [CI] eDVBCIInterfaces setInputSource(0, A)
<  1888.749> [CI] eDVBCIInterfaces setInputSource(1, B)
<  1888.750> [CI] done, found 2 common interface slots
<  1888.752> [CI] Streaming CI routing interface not advertised, assuming DVR method
<  1888.754> [CI] Streaming CI finish interface not advertised, assuming "tuner" method
<  1888.755> [eInit] + (35) CA handler
<  1888.755> [eServerSocket] ERROR on bind: No such file or directory
<  1888.756> [eInit] + (40) eServiceCenter
<  1888.757> [eServiceCenter] settings instance.
<  1888.757> [eInit] + (41) eServiceFactoryDVD
<  1888.758> [eInit] + (41) eServiceFactoryWebTS
<  1888.759> [eInit] + (41) eServiceFactoryTS
<  1888.759> [eInit] + (41) eServiceFactoryHDMI
<  1888.760> [eInit] + (41) eServiceFactoryM2TS
<  1888.761> [eInit] + (41) eServiceFactoryFS
<  1888.762> [eInit] + (41) eServiceFactoryDVB
<  1888.762> [eInit] + (41) Encoders
<  1888.763> [eInit] + (41) RTSP Stream server
<  1888.766> [eInit] + (41) Stream server
<  1888.769> [Avahi] avahi_timeout_new
<  1888.773> [Avahi] avahi_timeout_free
<  1888.775> [Avahi] avahi_timeout_new
<  1888.780> [Avahi] avahi_timeout_free
<  1888.785> [Avahi] avahi_timeout_new
<  1888.791> [Avahi] avahi_timeout_free
<  1888.794> [Avahi] avahi_timeout_new
<  1888.799> [Avahi] avahi_timeout_free
<  1888.801> [Avahi] avahi_timeout_new
<  1888.808> [Avahi] avahi_timeout_free
<  1888.809> [Avahi] Registered vusolo (_e2stream._tcp) on vusolo:8001
<  1888.809> [eInit] reached rl 70
<  1888.810> [eDVBDB] ---- opening lame channel db
<  1888.811> [eDVBDB] reading services (version 4)
<  1889.643> [eDVBDB] loaded 420 channels/transponders and 6992 services
<  1889.645> eDVBSatelliteEquipmentControl::clear()
<  1889.647> [eDVBResourceManager] scanning for frontends..
<  1889.648> [eDVBFrontend0] opening frontend
<  1889.649> [eDVBFrontend0] opening frontend
<  1889.650> [eDVBFrontend0] frontend 0 has DVB API 50a
<  1889.653> [eDVBFrontend0] close frontend
<  1889.656> [eDVBAdapterLinux] get demux 0
<  1889.656> [eDVBAdapterLinux] get demux 1
<  1889.657> [eDVBAdapterLinux] get demux 2
<  1889.658> [eDVBAdapterLinux] get demux 3
<  1889.658> [eDVBAdapterLinux] get demux 4
<  1889.659> [eDVBResourceManager] found 1 adapter, 1 frontends(1 sim) and 5 demux
<  1889.661> [eDVBLocalTimeHandler] RTC not ready... wait for transponder time
<  1889.662> [eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
<  1889.665> [MAIN] Loading spinners...
<  1889.683> [MAIN] found 6 spinner!
[MAIN] executing main
<  1889.687> [setIoPrio] best-effort level 3 ok
<  1890.669> [gRC] main thread is non-idle! display spinner!
<  1891.193> [mytest] Open Vision version = 9.3
<  1891.194> [mytest] Open Vision revision = r112
<  1891.254> [eDVBFrontend] Failed to open /dev/dbox/fp0
<  1891.255> [Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
<  1891.271> Traceback (most recent call last):
<  1891.272>   File "/usr/lib/enigma2/python/mytest.py", line 21, in <module>
<  1891.274>     from Components.SystemInfo import SystemInfo
<  1891.275>   File "/usr/lib/enigma2/python/Components/SystemInfo.py", line 125, in <module>
<  1891.276>   File "/usr/lib/enigma2/python/Tools/Multiboot.py", line 9, in getMultibootStartupDevice
<  1891.278> OSError: [Errno 2] No such file or directory: '/tmp/multibootcheck'
<  1891.294> [eDVBDB] ---- saving lame channel db
<  1893.059> [eDVBDB] saved 420 channels and 6992 services!
<  1893.079> [eDVBResourceManager] release cached channel (timer timeout)
<  1893.080> [Avahi] avahi_timeout_new
<  1893.087> [Avahi] avahi_timeout_free
<  1893.088> [Avahi] avahi_watch_free
<  1893.096> [Avahi] avahi_timeout_free
<  1893.097> [eInit] - (41) eServiceFactoryDVD
<  1893.100> [eInit] - (41) eServiceFactoryWebTS
<  1893.100> [eInit] - (41) eServiceFactoryTS
<  1893.101> [eInit] - (41) eServiceFactoryHDMI
<  1893.102> [eInit] - (41) eServiceFactoryM2TS
<  1893.102> [eInit] - (41) eServiceFactoryFS
<  1893.103> [eInit] - (41) eServiceFactoryDVB
<  1893.104> [eInit] - (41) Encoders
<  1893.105> [eInit] - (41) RTSP Stream server
<  1893.105> [eInit] - (41) Stream server
<  1893.106> [eInit] - (40) eServiceCenter
<  1893.107> [eServiceCenter] clear instance
<  1893.108> [eInit] - (35) CI Slots
<  1893.108> [eInit] - (35) CA handler
<  1893.109> [eInit] - (30) eActionMap
<  1893.110> [eInit] - (22) Hdmi CEC driver
<  1893.110> [eInit] - (21) input device driver
<  1893.112> [eInit] - (20) DVB-CI UI
<  1893.112> [eInit] - (20) UHF Modulator
<  1893.113> [eInit] - (20) RC Input layer
<  1893.113> [eInit] - (20) misc options
<  1893.114> [eInit] - (20) AVSwitch Driver
<  1893.114> [eInit] - (15) eWindowStyleManager
<  1893.114> [eInit] - (10) gRC
<  1893.117> [gRC] waiting for gRC thread shutdown
<  1893.117> [gRC] thread has finished
<  1893.118> [eInit] - (9) GFBDC
<  1893.126> [eInit] - (9) gLCD
<  1893.127> [eInit] - (9) Font Render Class
<  1893.128> [eInit] - (8) graphics acceleration manager
<  1893.129> [eInit] - (5) Tuxtxt
<  1893.129> [eInit] - (1) Background File Eraser
<  1893.131> [eInit] reached rl -1

**Comment by persianpros** [comment]
@Hains 

We need to act on this and remove multiboot check at startup once for all, it's not the first time I'm seeing this but recent PLi's changes to SystemInfo.py tries to find unreal things in so many STBs which is garbage code in my opinion (no offense to PLi).

Recent SystemInfo.py changes are for making multiboot functions easier but they made a mess and caused lots of boot loops.

**Comment by persianpros** [comment]
@ziko-ZR1 

Please compile and test a new image as want to know if https://github.com/OpenVisionE2/enigma2-openvision/commit/9c64f4836965dcd9f8358e458413cd599eec6513 helps you.

**Comment by ziko-ZR1** [comment]
@persianpros okay give me 1 hour and i will back to you

**Comment by persianpros** [comment]
Just use image.sh it will be fast.

**Comment by ziko-ZR1** [comment]
sorry it's the same and the tmp folder is not created 

![Screenshot from 2020-04-06 13-04-52](https://user-images.githubusercontent.com/43075184/78556720-61d9f680-7807-11ea-87f6-b9f7112b7f59.png)

**Comment by ziko-ZR1** [comment]
is there any updates about this problem ? 
thanks

**Comment by persianpros** [comment]
Compile and test a new image, https://github.com/OpenVisionE2/enigma2-openvision/commit/696efb99c8f2e7216245dd9e3cea69ca25687a74 should fix it.

If you still had problems open a new issue ;)
