### ISSUE TITLE
image on loop 

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/enigma2-openvision#48]
Open Vision Enigma2 crash log

crashdate=Tue Apr  7 20:52:52 2020
compiledate=Apr  7 2020
skin=Default Skin
sourcedate=2020-04-07
branch=develop
rev=696efb9
component=Enigma2

stbmodel=vusolo
stbbrand=vuplus
kernelcmdline=bmem=156M ubi.mtd=0 root=ubi0:rootfs rootfstype=ubifs rw rootflags=sync
nimsockets=NIM Socket 0:
visionversion=9.3
visionrevision=r113

<    96.635> :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

dmesg

<6>Detected MIPS clock frequency: 332 MHz (166.499 MHz counter)
<6>Console: colour dummy device 80x25
<6>Calibrating delay loop... 220.16 BogoMIPS (lpj=110080)
<6>pid_max: default: 32768 minimum: 301
<6>Mount-cache hash table entries: 512
<6>devtmpfs: initialized
<6>NET: Registered protocol family 16
<6>USB0: power enable is active high; overcurrent is active low
<6>PCI2.3->SDRAM window: 512 MB
<6>bio: create slab <bio-0> at 0
<5>SCSI subsystem initialized
<7>libata version 3.00 loaded.
<6>usbcore: registered new interface driver usbfs
<6>usbcore: registered new interface driver hub
<6>usbcore: registered new device driver usb
<6>Linux video capture interface: v2.00
<6>Advanced Linux Sound Architecture Driver Initialized.
<6>PCI host bridge to bus 0000:00
<6>pci_bus 0000:00: root bus resource [mem 0xd0000000-0xefffffff]
<6>pci_bus 0000:00: root bus resource [io  0x0400-0x83ff]
<6>pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
<7>pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
<6>cfg80211: Calling CRDA to update world regulatory domain
<6>Switching to clocksource upg
<5>FS-Cache: Loaded
<6>NET: Registered protocol family 2
<6>TCP established hash table entries: 2048 (order: 2, 16384 bytes)
<6>TCP bind hash table entries: 2048 (order: 1, 8192 bytes)
<6>TCP: Hash tables configured (established 2048 bind 2048)
<6>TCP: reno registered
<6>UDP hash table entries: 256 (order: 0, 4096 bytes)
<6>UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
<6>NET: Registered protocol family 1
<6>RPC: Registered named UNIX socket transport module.
<6>RPC: Registered udp transport module.
<6>RPC: Registered tcp transport module.
<6>RPC: Registered tcp NFSv4.1 backchannel transport module.
<7>PCI: CLS 0 bytes, default 128
<5>NFS: Registering the id_resolver key type
<5>Key type id_resolver registered
<5>Key type id_legacy registered
<6>fuse init (API version 7.21)
<6>msgmni has been set to 181
<6>io scheduler noop registered
<6>io scheduler cfq registered (default)
<6>Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
<6>serial8250.0: ttyS0 at MMIO 0x10400b00 (irq = 22) is a 16550A
<6>console [ttyS0] enabled, bootconsole disabled
<6>serial8250.0: ttyS1 at MMIO 0x10400b40 (irq = 66) is a 16550A
<6>loop: module loaded
<6>Broadcom STB NAND controller (BrcmNand Controller)
<6>bcmemac: Broadcom STB 10/100 EMAC driver v3.0
<6>bcmemac: registered interface #0 at 0x10080000 as 'eth0' (00:1d:ec:04:19:14)
<6>usbcore: registered new interface driver zd1201
<6>ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
<7>__clk_enable: usb [1]
<6>ehci-brcm ehci-brcm.0: Broadcom STB EHCI
<6>ehci-brcm ehci-brcm.0: new USB bus registered, assigned bus number 1
<6>ehci-brcm ehci-brcm.0: irq 62, io mem 0x10480300
<6>ehci-brcm ehci-brcm.0: USB 0.0 started, EHCI 1.00
<6>hub 1-0:1.0: USB hub found
<6>hub 1-0:1.0: 1 port detected
<6>ehci-brcm ehci-brcm.1: Broadcom STB EHCI
<6>ehci-brcm ehci-brcm.1: new USB bus registered, assigned bus number 2
<6>ehci-brcm ehci-brcm.1: irq 63, io mem 0x10480500
<6>ehci-brcm ehci-brcm.1: USB 0.0 started, EHCI 1.00
<6>hub 2-0:1.0: USB hub found
<6>hub 2-0:1.0: 1 port detected
<6>ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
<6>ohci-brcm ohci-brcm.0: Broadcom STB OHCI
<6>ohci-brcm ohci-brcm.0: new USB bus registered, assigned bus number 3
<6>ohci-brcm ohci-brcm.0: irq 64, io mem 0x10480400
<6>hub 3-0:1.0: USB hub found
<6>hub 3-0:1.0: 1 port detected
<6>ohci-brcm ohci-brcm.1: Broadcom STB OHCI
<6>ohci-brcm ohci-brcm.1: new USB bus registered, assigned bus number 4
<6>ohci-brcm ohci-brcm.1: irq 59, io mem 0x10480600
<6>hub 4-0:1.0: USB hub found
<6>hub 4-0:1.0: 1 port detected
<6>Initializing USB Mass Storage driver...
<6>usbcore: registered new interface driver usb-storage
<6>USB Mass Storage support registered.
<6>mousedev: PS/2 mouse device common for all mice
<6>i2c /dev entries driver
<6>hidraw: raw HID events driver (C) Jiri Kosina
<6>usbcore: registered new interface driver usbhid
<6>usbhid: USB HID core driver
<6>TCP: cubic registered
<6>NET: Registered protocol family 17
<5>Key type dns_resolver registered
<6>EBI CS0: setting up NAND flash (primary)
<6>mtd->oobsize=0, mtd->eccOobSize=0
<4>NAND_CS_NAND_XOR=00000001
<4>B4: NandSelect=40000101, nandConfig=55042200, chipSelect=0
<4>brcmnand_read_id: CS0: dev_id=ecf10095
<4>After: NandSelect=40000101, nandConfig=55042200
<4>Block size=00020000, erase shift=17
<6>NAND Config: Reg=55042200, chipSize=128 MB, blockSize=128K, erase_shift=11
<6>busWidth=1, pageSize=2048B, page_shift=11, page_mask=000007ff
<6>BrcmNAND mfg ec f1 Samsung K9F1G08U0A 128MB on CS0
<6>
<6>Found NAND on CS0: ACC=d3000000, cfg=55042200, flashId=ecf10095, tim1=4232222d, tim2=00000d94
<6>BrcmNAND version = 0x0200 128MB @00000000
<4>B4: NandSelect=40000101, nandConfig=55042200, chipSelect=0
<4>brcmnand_read_id: CS0: dev_id=ecf10095
<4>After: NandSelect=40000101, nandConfig=55042200
<4>Found NAND flash on Chip Select 0, chipSize=128MB, usable size=128MB, base=0
<4>brcmnand_scan: B4 nand_select = 40000101
<4>brcmnand_scan: After nand_select = 40000101
<6>page_shift=11, bbt_erase_shift=17, chip_shift=27, phys_erase_shift=17
<6>Brcm NAND controller version = 2.0 NAND flash size 128MB @18000000
<4>ECC layout=brcmnand_oob_bch4_4k
<6>brcmnand_scan:  mtd->oobsize=64
<6>brcmnand_scan: oobavail=50, eccsize=512, writesize=2048
<6>brcmnand_scan, eccsize=512, writesize=2048, eccsteps=4, ecclevel=15, eccbytes=3
<4>-->brcmnand_default_bbt
<4>brcmnand_default_bbt: bbt_td = bbt_main_descr
<7>Bad block table Bbt0 found at page 0000ffc0, version 0x01 for chip on CS0
<7>Bad block table 1tbB found at page 0000ff80, version 0x01 for chip on CS0
<7>nand_read_bbt: Bad block at 0x00f00000
<7>nand_read_bbt: Bad block at 0x07560000
<5>Creating 7 MTD partitions on "brcmnand.0":
<5>0x000000000000-0x000007400000 : "rootfs"
<5>0x000007400000-0x000007800000 : "kernel"
<5>0x000007800000-0x000007c00000 : "boot"
<5>0x000007c00000-0x000007d00000 : "cfe"
<5>0x000007d00000-0x000007d80000 : "mac"
<5>0x000007d80000-0x000007e00000 : "env"
<5>0x000007e00000-0x000007f00000 : "nvm"
<6>PM: CP0 COUNT/COMPARE frequency depends on divisor
<5>UBI: attaching mtd0 to ubi0
<5>UBI: scanning is finished
<5>UBI: volume 0 ("rootfs") re-sized from 876 to 904 LEBs
<5>UBI: attached mtd0 (name "rootfs", size 116 MiB) to ubi0
<5>UBI: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
<5>UBI: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
<5>UBI: VID header offset: 2048 (aligned 2048), data offset: 4096
<5>UBI: good PEBs: 927, bad PEBs: 1, corrupted PEBs: 0
<5>UBI: user volume: 1, internal volumes: 1, max. volumes count: 128
<5>UBI: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 814248072
<5>UBI: available PEBs: 0, total reserved PEBs: 927, PEBs reserved for bad PEB handling: 19
<6>ALSA device list:
<6>  No soundcards found.
<5>UBIFS: parse sync
<5>UBI: background thread "ubi_bgt0d" started, PID 37
<5>UBIFS: background thread "ubifs_bgt0_0" started, PID 38
<5>UBIFS: start fixing up free space
<5>UBIFS: free space fixup complete
<5>UBIFS: mounted UBI device 0, volume 0, name "rootfs"(null)
<5>UBIFS: LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
<5>UBIFS: FS size: 113389568 bytes (108 MiB, 893 LEBs), journal size 9023488 bytes (8 MiB, 72 LEBs)
<5>UBIFS: reserved for root: 0 bytes (0 KiB)
<5>UBIFS: media format: w4/r0 (latest is w4/r0), UUID C49D4AEC-3EB1-4BC7-B866-0FDA60937144, small LPT model
<6>VFS: Mounted root (ubifs filesystem) on device 0:10.
<6>devtmpfs: mounted
<6>Freeing unused kernel memory: 228k freed
<4>procmk_init
<4>dvb_bcm7325: module license 'Proprietary' taints kernel.
<4>Disabling lock debugging due to kernel taint
<6>DVB: registering new adapter (vusolo)
<4>bcm7325: hotplug_callback(): 
<4>Hotplug - status.connected 1
<4>bcm7325: hotplug_callback(): 
<4>Hotplug - connecting HDMI to display 0xe
<6>brcm_demux_init: $Id: bcm7335_demux.c,v 0.6 $
<4>[VID]: 6bcm7335_video_init
<4>[AUD]: 6bcm7335_audio_init
<6>BRCM brcm_dvb0: DVB: registering adapter 0 frontend 0 (BCM7335 FE)...
<4>[MPVR]: >> misc_pvr_init
<6>input: dreambox remote control (native) as /devices/virtual/input/input0
<6>[LCD]: registered
<4>[LCD]:power led off
<4>
<4>[LCD]:bm730_dbox_lcd_write_data 
<4>
<4>[LCD]:vfd reply success
<4>
<6>[CI]: registered ci0
<6>[CI]: registered ci1
<6>[DFP]: registered dbox fp
<4>[DFP]:max9597_Shutdown data = 0x80
<6>[SC]: registered sci0
<4>system_time_set wakeup mode get 
<4>[LCD]:bm730_dbox_lcd_write_read_data len: 8
<4>
<4>[LCD]:rtc data received 4
<4>
<4>system_time_set wakeup mode get 0xc4
<4>[LCD]:bm730_dbox_lcd_write_read_data len: 8
<4>
<4>[LCD]:rtc data received 4
<4>
<6>NET: Registered protocol family 10
<4>[VID]: VIDEO_SET_STREAMTYPE 0 
<4>[VID]: VIDEO_SELECT_SOURCE 1  
<4>[VID]: VIDEO_PLAY 1  2 0
<4>[VID]: VIDEO_CONTINUE 1  1 
<4>[VID]: VIDEO_CLEAR_BUFFER 1  1 0
<4>[VID]: VIDEO_STOP 0  1
<4>[VID]: VIDEO_SELECT_SOURCE 0  
<4>[LCD]:bm730_dbox_lcd_write_data 
<4>
<4>[LCD]:vfd reply success
<4>
<4>[LCD]:bm730_dbox_lcd_write_read_data len: 8
<4>
<4>[LCD]:rtc data received 4
<4>
<4>[LCD]:dbox_lcd_open
<4>
<4>[LCD]:dbox_lcd_ioctl cmd : 4117
<4>
<3>[LCD]: unknown cmd 0x1015
<4>[CI]:ci_dev_open
<4>
<4>[CI]:Opening A GPIO's for 7325 platform
<4>
<4>[CI]:Opening A GPIO's for 7325 platform....done
<4>
<4>[CI]:entering.. A NEXUS_DvbCi_Open 
<4>
<4>[CI]:NEXUS_DvbCi_Open done..
<4>
<4>[CI]:Installing callbacks
<4>
<4>[CI]:Forcing card check
<4>
<4>[CI]:Card insertion status changed
<4>
<4>[CI]:Opening B GPIO's for 7325 platform
<4>
<4>[CI]:Opening B GPIO's for 7325 platform....done
<4>
<4>[CI]:entering.. B NEXUS_DvbCi_Open 
<4>
<4>[CI]:NEXUS_DvbCi_Open done..
<4>
<4>[CI]:Installing callbacks
<4>
<4>[CI]:Forcing card check
<4>
<4>[CI]:Card B insertion status changed
<4>
<6>[CI]: CI interface initialised
<6>
<4>[CI]:ci1_dev_open
<4>
<4>[CI]:NEXUS_Remux_Start CI0 0 0
<4>
<4>[CI]:>>close_mpod tuner:0
<4>
<4>[CI]:remux stop
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt() count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt() count : 0
<4>
<4>[CI]:>>close_mpod tuner:1
<4>
<4>[CI]:remux stop
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt() count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt count : 0
<4>
<4>[CI]:get_remux_startcnt() count : 0
<4>
<4>[DFP]:scart_select_tvvideotype TV = 0
<4>[DFP]:max9597_fast_blanking data = 0x0
<4>[DFP]:max9597_enable_output data = 0x6
<4>[DFP]:scart_select_tvout aTVOutType = 2
<4>[LCD]:bm730_dbox_lcd_write_data 
<4>
<4>[LCD]:vfd reply success
<4>
<4>[LCD]:bm730_dbox_lcd_write_data 
<4>
<4>[LCD]:vfd reply success
<4>
<4>[LCD]:bm730_dbox_lcd_write_data 
<4>
<4>[LCD]:vfd reply success
<4>
<4>[AUD]: AUDIO_SET_MUTE 0 
<4>[AUD]: AUDIO_SET_MIXER -2055315976 
<4>[DFP]:scart_select_screentype aRatio = 2
<4>[DFP]:max9597_slow_blanking data = 0x1
<4>[DFP]:scart_select_screentype aRatio = 2
<4>[DFP]:max9597_slow_blanking data = 0x1
<4>[DFP]:scart_select_screentype aRatio = 2
<4>[DFP]:max9597_slow_blanking data = 0x1
<4>[DFP]:scart_select_screentype aRatio = 2
<4>[DFP]:max9597_slow_blanking data = 0x1
<4>[DFP]:scart_select_screentype aRatio = 2
<4>[DFP]:max9597_slow_blanking data = 0x1

**Comment by persianpros** [comment]
Install "python-service-identity" and let me know if it fixes the problem.

**Comment by ziko-ZR1** [comment]
thanks but i removed the image i will wait for the final fix , this can be closed

**Comment by persianpros** [comment]
You need to compile and test after https://github.com/OpenVisionE2/openvision-development-platform/commit/6c82e8df3a425ebd08fc6d54fd9c1f7cce02a0be
