### ISSUE TITLE
image still in loop | vusolo

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/enigma2-openvision#49]
<   448.627> [Avahi] avahi_timeout_new
<   448.629> [Avahi] avahi_watch_new(3 0x1)
<   448.631> [Avahi] avahi_timeout_new
<   448.637> [Avahi] avahi_timeout_free
<   448.639> [Avahi] avahi_timeout_update
<   448.642> [Avahi] avahi_timeout_new
<   448.645> [Avahi] avahi_timeout_free
<   448.647> [Avahi] avahi_timeout_new
<   448.652> [Avahi] avahi_timeout_free
<   448.653> [Avahi] avahi_timeout_new
<   448.657> [Avahi] avahi_timeout_free
<   448.659> [Avahi] avahi_timeout_new
<   448.666> [Avahi] avahi_timeout_free
<   448.667> [Avahi] avahi_timeout_new
<   448.672> [Avahi] avahi_timeout_free
<   448.675> [Avahi] client state: 2
<   448.677> [Avahi] avahi_timeout_new
<   448.683> [Avahi] avahi_timeout_free
<   448.690> [eInit] + (1) Background File Eraser
<   448.691> [eInit] + (5) Tuxtxt
<   448.692> [eInit] + (8) graphics acceleration manager
<   448.714> [eInit] + (9) GFBDC
<   448.714> [fb] /dev/fb0: 21600k video mem
<   448.715> [fb] 21600k video mem
<   448.716> [fb] double buffering available!
<   448.720> [fb] 2 page(s) available!
<   448.934> [gFBDC] resolution: 1920 x 1080 x 32 (stride: 7680) pages: 2
<   448.934> [gFBDC] 5400kB available for acceleration surfaces.
<   448.935> [eInit] + (9) gLCD
<   448.936> [eFbLCD] /dev/fb1: No such file or directory
<   448.937> [eFbLCD] framebuffer /dev/fb1 not available
<   448.952> [eLCD] xres=132, yres=64, bpp=8 lcd_type=1
<   448.953> [eLCD] (132x64x8) buffer 0x822d70 8448 bytes, stride 132
<   448.954> [gLCDDC] resolution: 132x64x8 stride=132
<   448.957> [eInit] + (9) Font Render Class
<   448.957> [Font] Initializing lib.
<   448.958> [Font] Loading fonts.
<   448.959> [Font] Intializing font cache, using max. 4MB.
<   448.959> [eInit] + (10) gRC
<   448.962> [gRC] thread created successfully
<   448.965> [eInit] + (15) eWindowStyleManager
<   448.965> [eInit] + (20) DVB-CI UI
<   448.966> [eInit] + (20) UHF Modulator
<   448.967> [eRFmod] couldnt open /dev/rfmod0: No such file or directory
<   448.967> [eInit] + (20) RC Input layer
<   448.967> [eInit] + (20) misc options
<   448.968> [eInit] + (20) AVSwitch Driver
<   448.972> [eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: No such file or directory
<   448.972> [eInit] + (21) input device driver
<   448.973> [eInputDeviceInit] adding device /dev/input/event0
<   448.974> [eRCInputEventDriver] devicename=dreambox remote control (native)
<   448.981> [eRCInputEventDriver] devicename=dreambox remote control (native)
<   448.981> [eRCInputEventDriver] EVIOCGRAB: Device or resource busy
<   448.982> [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
<   448.982> [eInputDeviceInit] Found 1 input devices.
<   448.983> [eInit] + (22) Hdmi CEC driver
<   448.983> [eHdmiCEC] cannot open /dev/hdmi_cec: Device or resource busy
<   448.984> [eInit] + (30) eActionMap
<   448.984> [eInit] + (35) CI Slots
<   448.985> [eServerSocket] ERROR on bind: No such file or directory
<   448.987> [CI] scanning for common interfaces..
<   449.008> [CI] Slot: 0 setSource: A
<   449.009> [CI] Slot: 1 setSource: A
<   449.039> [CI] eDVBCIInterfaces setInputSource(0, A)
<   449.069> [CI] eDVBCIInterfaces setInputSource(1, B)
<   449.071> [CI] done, found 2 common interface slots
<   449.075> [CI] Streaming CI routing interface not advertised, assuming DVR method
<   449.077> [CI] Streaming CI finish interface not advertised, assuming "tuner" method
<   449.077> [eInit] + (35) CA handler
<   449.078> [eServerSocket] ERROR on bind: No such file or directory
<   449.081> [eInit] + (40) eServiceCenter
<   449.081> [eServiceCenter] settings instance.
<   449.082> [eInit] + (41) eServiceFactoryDVD
<   449.082> [eInit] + (41) eServiceFactoryWebTS
<   449.083> [eInit] + (41) eServiceFactoryTS
<   449.084> [eInit] + (41) eServiceFactoryHDMI
<   449.085> [eInit] + (41) eServiceFactoryM2TS
<   449.087> [eInit] + (41) eServiceFactoryFS
<   449.087> [eInit] + (41) eServiceFactoryDVB
<   449.088> [eInit] + (41) Encoders
<   449.089> [eInit] + (41) RTSP Stream server
<   449.092> [eServerSocket] ERROR on bind: Address already in use
<   449.093> [eServerSocket] ERROR on bind: Address already in use
<   449.094> [eInit] + (41) Stream server
<   449.096> [eServerSocket] ERROR on bind: Address already in use
<   449.099> [eServerSocket] ERROR on bind: Address already in use
<   449.108> [Avahi] avahi_timeout_new
<   449.114> [Avahi] avahi_timeout_free
<   449.118> [Avahi] avahi_timeout_new
<   449.127> [Avahi] avahi_timeout_free
<   449.131> [Avahi] avahi_timeout_new
<   449.138> [Avahi] avahi_timeout_free
<   449.146> [Avahi] avahi_timeout_new
<   449.151> [Avahi] avahi_timeout_free
<   449.153> [Avahi] avahi_timeout_new
<   449.162> [Avahi] avahi_timeout_free
<   449.163> [Avahi] Registered vusolo (_e2stream._tcp) on vusolo:8001
<   449.164> [eInit] reached rl 70
<   449.165> [eDVBDB] ---- opening lame channel db
<   449.166> [eDVBDB] reading services (version 4)
<   450.968> [gRC] main thread is non-idle! display spinner!
<   450.969> [gRC] enabelSpinner: no spinner DC!
<   451.090> [eDVBDB] loaded 420 channels/transponders and 6992 services
<   451.091> eDVBSatelliteEquipmentControl::clear()
<   451.092> [eDVBResourceManager] scanning for frontends..
<   451.095> [eDVBFrontend0] opening frontend
<   451.096> [eDVBFrontend0] opening frontend
<   451.106> [eDVBFrontend0] frontend 0 has DVB API 50a 
<   451.108> [eDVBFrontend0] close frontend
<   451.111> [eDVBAdapterLinux] get demux 0
<   451.111> [eDVBAdapterLinux] get demux 1
<   451.111> [eDVBAdapterLinux] get demux 2
<   451.113> [eDVBAdapterLinux] get demux 3
<   451.114> [eDVBAdapterLinux] get demux 4
<   451.117> [eDVBResourceManager] found 1 adapter, 1 frontends(1 sim) and 5 demux
<   451.118> [eDVBLocalTimeHandler] RTC not ready... wait for transponder time
<   451.119> [eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
<   451.123> [MAIN] Loading spinners...
<   451.157> [MAIN] found 6 spinner!
[MAIN] executing main
<   451.161> [setIoPrio] best-effort level 3 ok
<   452.969> [gRC] main thread is non-idle! display spinner!
<   454.657> [mytest] Open Vision version = 9.3
<   454.658> [mytest] Open Vision revision = r113
<   454.747> [eDVBFrontend] Failed to open /dev/dbox/fp0
<   454.749> [Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
<   457.343> [Harddisk] enumerating block devices...
<   457.623> [Harddisk] enumerating network mounts...
<   457.829> [ClientMode] Client mode data initialised.
<   458.341> [StbHardware] getFPVersion failed!
<   458.438> [skin] Warning: Skin file 'skin_user.xml' does not exist!
<   460.198> [skin] Skin '/usr/share/enigma2/OctEtFHD/skin.xml' added successfully.
<   460.254> [skin] Skin '/usr/share/enigma2/display/skin_default/skin_display.xml' added successfully.
<   460.275> [skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
<   460.962> [skin] Skin '/usr/share/enigma2/skin_default/skin.xml' added successfully.
<   470.017> [NimManager] Reading satellites.xml
<   475.332> eDVBSatelliteEquipmentControl::clear()
<   475.337> [NimManager] sec config cleared
<   475.338> [eDVBFrontend] setSlotInfo for dvb frontend 0 to slotid 0, descr BCM7325 DVB-S2 NIM (internal), need rotorworkaround No, enabled Yes, DVB-S2 Yes
<   475.344> [NimManager] slot: 0 configmode: simple
<   475.345> [eDVBSatelliteEquipmentControl::setSlotNotLinked] slot=0
<   475.350> [NimManager] diseqcmode:  diseqc_a_b_c_d
<   475.353> [eDVBSatelliteEquipmentControl::addLNB] lnb=0)
<   475.359> eDVBSatelliteEquipmentControl::setLNBSatCRformat(0)
<   475.359> [eDVBSatelliteEquipmentControl::setLNBNum] lnbnum=1
<   475.364> [eDVBSatelliteEquipmentControl::setLNBLOFL] logfl=9750000
<   475.364> [eDVBSatelliteEquipmentControl::setLNBLOFH] lofh=10600000
<   475.365> [eDVBSatelliteEquipmentControl::setLNBThreshold] threshold=11700000
<   475.366> [eDVBSatelliteEquipmentControl::setLNBIncreasedVoltage] onoff=0
<   475.367> [eDVBSatelliteEquipmentControl::setRepeats] repeat=0
<   475.367> [eDVBSatelliteEquipmentControl::setFastDiSEqc] onoff=0
<   475.368> [eDVBSatelliteEquipmentControl::setSeqRepeat] onoff=0
<   475.368> [eDVBSatelliteEquipmentControl::setCommandOrder] order=0
<   475.369> [eDVBSatelliteEquipmentControl::setDiSEqcMode] mode=1
<   475.371> [eDVBSatelliteEquipmentControl::setToneburst] toneburst=0
<   475.372> [eDVBSatelliteEquipmentControl::setCommittedCommand] command=0
<   475.372> [eDVBSatelliteEquipmentControl::setUncommittedCommand] command=0
<   475.373> [eDVBSatelliteEquipmentControl::addSatellite] orb_pos=192
<   475.374> [eDVBSatelliteEquipmentControl::setVoltageMode] mode=0
<   475.386> [eDVBSatelliteEquipmentControl::setToneMode] mode=0
<   475.387> [eDVBSatelliteEquipmentControl::setLNBSlotMask] slotmask=1
<   475.388> [eDVBSatelliteEquipmentControl::addLNB] lnb=1)
<   475.391> eDVBSatelliteEquipmentControl::setLNBSatCRformat(0)
<   475.392> [eDVBSatelliteEquipmentControl::setLNBNum] lnbnum=1
<   475.393> [eDVBSatelliteEquipmentControl::setLNBLOFL] logfl=9750000
<   475.394> [eDVBSatelliteEquipmentControl::setLNBLOFH] lofh=10600000
<   475.396> [eDVBSatelliteEquipmentControl::setLNBThreshold] threshold=11700000
<   475.397> [eDVBSatelliteEquipmentControl::setLNBIncreasedVoltage] onoff=0
<   475.398> [eDVBSatelliteEquipmentControl::setRepeats] repeat=0
<   475.398> [eDVBSatelliteEquipmentControl::setFastDiSEqc] onoff=0
<   475.399> [eDVBSatelliteEquipmentControl::setSeqRepeat] onoff=0
<   475.399> [eDVBSatelliteEquipmentControl::setCommandOrder] order=0
<   475.401> [eDVBSatelliteEquipmentControl::setDiSEqcMode] mode=1
<   475.401> [eDVBSatelliteEquipmentControl::setToneburst] toneburst=0
<   475.405> [eDVBSatelliteEquipmentControl::setCommittedCommand] command=1
<   475.405> [eDVBSatelliteEquipmentControl::setUncommittedCommand] command=0
<   475.406> [eDVBSatelliteEquipmentControl::addSatellite] orb_pos=130
<   475.407> [eDVBSatelliteEquipmentControl::setVoltageMode] mode=0
<   475.407> [eDVBSatelliteEquipmentControl::setToneMode] mode=0
<   475.411> [eDVBSatelliteEquipmentControl::setLNBSlotMask] slotmask=1
<   475.412> [eDVBSatelliteEquipmentControl::addLNB] lnb=2)
<   475.413> eDVBSatelliteEquipmentControl::setLNBSatCRformat(0)
<   475.414> [eDVBSatelliteEquipmentControl::setLNBNum] lnbnum=1
<   475.414> [eDVBSatelliteEquipmentControl::setLNBLOFL] logfl=9750000
<   475.415> [eDVBSatelliteEquipmentControl::setLNBLOFH] lofh=10600000
<   475.415> [eDVBSatelliteEquipmentControl::setLNBThreshold] threshold=11700000
<   475.415> [eDVBSatelliteEquipmentControl::setLNBIncreasedVoltage] onoff=0
<   475.416> [eDVBSatelliteEquipmentControl::setRepeats] repeat=0
<   475.416> [eDVBSatelliteEquipmentControl::setFastDiSEqc] onoff=0
<   475.416> [eDVBSatelliteEquipmentControl::setSeqRepeat] onoff=0
<   475.417> [eDVBSatelliteEquipmentControl::setCommandOrder] order=0
<   475.417> [eDVBSatelliteEquipmentControl::setDiSEqcMode] mode=1
<   475.418> [eDVBSatelliteEquipmentControl::setToneburst] toneburst=0
<   475.418> [eDVBSatelliteEquipmentControl::setCommittedCommand] command=2
<   475.418> [eDVBSatelliteEquipmentControl::setUncommittedCommand] command=0
<   475.419> [eDVBSatelliteEquipmentControl::addSatellite] orb_pos=282
<   475.419> [eDVBSatelliteEquipmentControl::setVoltageMode] mode=0
<   475.419> [eDVBSatelliteEquipmentControl::setToneMode] mode=0
<   475.419> [eDVBSatelliteEquipmentControl::setLNBSlotMask] slotmask=1
<   475.424> [eDVBSatelliteEquipmentControl::addLNB] lnb=3)
<   475.425> eDVBSatelliteEquipmentControl::setLNBSatCRformat(0)
<   475.425> [eDVBSatelliteEquipmentControl::setLNBNum] lnbnum=1
<   475.426> [eDVBSatelliteEquipmentControl::setLNBLOFL] logfl=9750000
<   475.426> [eDVBSatelliteEquipmentControl::setLNBLOFH] lofh=10600000
<   475.426> [eDVBSatelliteEquipmentControl::setLNBThreshold] threshold=11700000
<   475.427> [eDVBSatelliteEquipmentControl::setLNBIncreasedVoltage] onoff=0
<   475.427> [eDVBSatelliteEquipmentControl::setRepeats] repeat=0
<   475.427> [eDVBSatelliteEquipmentControl::setFastDiSEqc] onoff=0
<   475.429> [eDVBSatelliteEquipmentControl::setSeqRepeat] onoff=0
<   475.429> [eDVBSatelliteEquipmentControl::setCommandOrder] order=0
<   475.430> [eDVBSatelliteEquipmentControl::setDiSEqcMode] mode=1
<   475.431> [eDVBSatelliteEquipmentControl::setToneburst] toneburst=0
<   475.431> [eDVBSatelliteEquipmentControl::setCommittedCommand] command=3
<   475.432> [eDVBSatelliteEquipmentControl::setUncommittedCommand] command=0
<   475.432> [eDVBSatelliteEquipmentControl::addSatellite] orb_pos=3300
<   475.439> [eDVBSatelliteEquipmentControl::setVoltageMode] mode=0
<   475.442> [eDVBSatelliteEquipmentControl::setToneMode] mode=0
<   475.443> [eDVBSatelliteEquipmentControl::setLNBSlotMask] slotmask=1
<   475.445> [NimManager] sec config completed
<   476.832> [MovieSelection] Bluray Player is not installed: cannot import name BlurayPlayer
<   479.864> [InfoBarGenerics] Failed to load resumepoints: [Errno 2] No such file or directory: '/etc/enigma2/resumepoints.pkl'
<   480.106> [eDVBDB] loading bouquet... /etc/enigma2//bouquets.tv
<   480.114> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.ec_maroc.tv
<   480.127> [eDVBDB] 7 entries in Bouquet userbouquet.ec_maroc.tv
<   480.129> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.tv
<   480.147> [eDVBDB] 87 entries in Bouquet userbouquet.favourites.tv
<   480.149> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.dbe00.tv
<   480.153> [eDVBDB] 2 entries in Bouquet userbouquet.dbe00.tv
<   480.154> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.ec_osn.tv
<   480.162> [eDVBDB] 50 entries in Bouquet userbouquet.ec_osn.tv
<   480.165> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.ec_elcinema.tv
<   480.191> [eDVBDB] 36 entries in Bouquet userbouquet.ec_elcinema.tv
<   480.191> [eDVBDB] 5 entries in Bouquet bouquets.tv
<   480.232> [eDVBDB] loading bouquet... /etc/enigma2//bouquets.radio
<   480.237> [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.radio
<   480.240> [eDVBDB] 0 entries in Bouquet userbouquet.favourites.radio
<   480.250> [eDVBDB] 1 entries in Bouquet bouquets.radio
<   480.251> [eDVBDB] Renumbering...
<   480.521> [mytest] Time By: Transponder
<   480.526> [eEPGCache] time updated.. but cache file not set yet.. dont start epg!!
<   480.551> [Console] command: /usr/bin/ntpdate-sync
<   480.552> [eConsoleAppContainer] Starting /bin/sh
<   506.203> [StackTrace] initializing StackTracePrinter
<   506.276> [fb] double buffering available!
<   506.276> [fb] 2 page(s) available!
<   506.401> [gFBDC] resolution: 720 x 576 x 32 (stride: 7680) pages: 2
<   506.405> [gFBDC] 12960kB available for acceleration surfaces.
<   507.051> [Font] Adding font /usr/share/fonts/nmsbd.ttf[Font] OK (Regular)<   507.369> [Font] Adding font /usr/share/fonts/andale.ttf[Font] OK (Fixed)<   507.627> [Font] Adding font /usr/share/fonts/tuxtxt.ttf[Font] OK (Console)<   508.035> [Font] Adding font /usr/share/fonts/DejaVuSans.ttf[Font] OK (DejaVuSans)<   508.124> [Font] Adding font /usr/share/fonts/ae_AlMateen.ttf[Font] OK (Replacement)<   508.185> [Font] Adding font /usr/share/fonts/fallback.font[Font] OK (Fallback)<   508.779> [Font] Adding font /usr/share/fonts/LiberationSans-Regular.ttf[Font] OK (Subs)<   508.833> [Font] Adding font /usr/share/fonts/LiberationSans-Italic.ttf[Font] OK (Subsi)<   508.903> [Font] Adding font /usr/share/fonts/LiberationSans-Bold.ttf[Font] OK (Subsb)<   509.227> [Font] Adding font /usr/share/fonts/LiberationSans-BoldItalic.ttf[Font] OK (Subsz)<   509.628> [Font] Adding font /usr/share/fonts/fallback.font[Font] OK (Fallback)<   510.221> [fb] double buffering available!
<   510.239> [fb] 2 page(s) available!
<   510.586> [gFBDC] resolution: 1920 x 1080 x 32 (stride: 7680) pages: 2
<   510.646> [gFBDC] 5400kB available for acceleration surfaces.
<   510.811> [skin] Loading included file '/usr/share/enigma2/OctEtFHD/skin_media.xml'.
<   511.536> [skin] Load skin screen name 'EnhancedMovieCenterMenu' added to the skin.
<   511.550> [skin] Load skin screen name 'EMCSelection' added to the skin.
<   511.554> [skin] Load skin screen name 'EMCMediaCenter' added to the skin.
<   511.555> [skin] Load skin screen name 'InfoBarEventView' added to the skin.
<   511.562> [skin] Load skin screen name 'EventViewSimple' added to the skin.
<   511.563> [skin] Load skin screen name 'EventViewContextMenu' already exists in the skin and has been skipped.
<   511.564> [skin] Load skin screen name 'EMCPlaylistSetup' added to the skin.
<   512.035> [skin] Load skin screen name 'EMCPlaylist' added to the skin.
<   512.127> [skin] Load skin screen name 'EMCFileBrowser' added to the skin.
<   512.128> [skin] Load skin screen name 'EMCImdbScan' added to the skin.
<   512.133> [skin] Load skin screen name 'imdbSetup' added to the skin.
<   512.142> [skin] Load skin screen name 'getCover' added to the skin.
<   512.147> [skin] Load skin screen name 'DownloadMovieInfo' added to the skin.
<   512.152> [skin] Load skin screen name 'MovieInfoPreview' added to the skin.
<   512.158> [skin] Load skin screen name 'MovieInfoSetup' added to the skin.
<   512.172> [skin] Load skin screen name 'MovieInfoTMDb' added to the skin.
<   512.181> [skin] Load skin screen name 'IMDB' added to the skin.
<   512.300> [skin] Loading included file '/usr/share/enigma2/OctEtFHD/skin_plugins.xml'.

**Comment by persianpros** [comment]
Is the image itself ok without restoring any backups?

**Comment by ziko-ZR1** [comment]
No, it's not okay the problem start after r95 it was okay back then I still have it, but it has some small problems like I cannot install ipk's from the menu and I had to restart the network after every boot up, so I decided to update the image from r95 to r113 and this problem appear, I cleaned up everything nothing change

**Comment by persianpros** [comment]
Hmm I can't find the problem in your logs ...

**Comment by ziko-ZR1** [comment]
check this maybe it can help :
https://github.com/OpenVisionE2/openvision-development-platform/issues/65#issuecomment-612503874

**Comment by ziko-ZR1** [comment]
is there anything else i can do ??

**Comment by persianpros** [comment]
Let me compile an image for you and test my build, I want to be sure about something.

**Comment by persianpros** [comment]
Check this file: http://www.mediafire.com/file/f2f8jtm2d11e80o/openvision-enigma2-develop-multilanguage-9.3-r117-vusolo_usb.zip/file

**Comment by ziko-ZR1** [comment]
same result as before , again tmp file is not created correctly and the image stucked at boot logo .
<   285.554> [Avahi] avahi_timeout_new
<   285.555> [Avahi] avahi_watch_new(3 0x1)
<   285.556> [Avahi] avahi_timeout_update
<   285.558> [Avahi] avahi_timeout_new
<   285.561> [Avahi] avahi_timeout_free
<   285.563> [Avahi] avahi_timeout_new
<   285.566> [Avahi] avahi_timeout_free
<   285.567> [Avahi] avahi_timeout_new
<   285.570> [Avahi] avahi_timeout_free
<   285.571> [Avahi] avahi_timeout_new
<   285.576> [Avahi] avahi_timeout_free
<   285.577> [Avahi] avahi_timeout_new
<   285.581> [Avahi] avahi_timeout_free
<   285.582> [Avahi] avahi_timeout_new
<   285.587> [Avahi] avahi_timeout_free
<   285.587> [Avahi] client state: 2
<   285.590> [Avahi] avahi_timeout_new
<   285.601> [Avahi] avahi_timeout_free
<   285.605> [eInit] + (1) Background File Eraser
<   285.607> [eInit] + (5) Tuxtxt
<   285.608> [eInit] + (8) graphics acceleration manager
<   285.622> [eInit] + (9) GFBDC
<   285.623> [fb] /dev/fb0: 21600k video mem
<   285.624> [fb] 21600k video mem
<   285.626> [fb] double buffering available!
<   285.626> [fb] 2 page(s) available!
<   285.680> [gFBDC] resolution: 720 x 576 x 32 (stride: 7680) pages: 2
<   285.681> [gFBDC] 12960kB available for acceleration surfaces.
<   285.681> [eInit] + (9) gLCD
<   285.682> [eFbLCD] /dev/fb1: No such file or directory
<   285.683> [eFbLCD] framebuffer /dev/fb1 not available
<   285.694> [eLCD] xres=132, yres=64, bpp=8 lcd_type=1
<   285.694> [eLCD] (132x64x8) buffer 0x822d70 8448 bytes, stride 132
<   285.695> [gLCDDC] resolution: 132x64x8 stride=132
<   285.696> [eInit] + (9) Font Render Class
<   285.696> [Font] Initializing lib.
<   285.697> [Font] Loading fonts.
<   285.698> [Font] Intializing font cache, using max. 4MB.
<   285.699> [eInit] + (10) gRC
<   285.700> [gRC] thread created successfully
<   285.701> [eInit] + (15) eWindowStyleManager
<   285.701> [eInit] + (20) DVB-CI UI
<   285.702> [eInit] + (20) UHF Modulator
<   285.702> [eRFmod] couldnt open /dev/rfmod0: No such file or directory
<   285.703> [eInit] + (20) RC Input layer
<   285.703> [eInit] + (20) misc options
<   285.703> [eInit] + (20) AVSwitch Driver
<   285.703> [eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: No such file or directory
<   285.703> [eInit] + (21) input device driver
<   285.703> [eInputDeviceInit] adding device /dev/input/event0
<   285.704> [eRCInputEventDriver] devicename=dreambox remote control (native)
<   285.705> [eRCInputEventDriver] devicename=dreambox remote control (native)
<   285.706> [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
<   285.707> [eInputDeviceInit] Found 1 input devices.
<   285.707> [eInit] + (22) Hdmi CEC driver
<   285.708> [eHdmiCEC] detected physical address change: 1000 --> FFFF
<   285.709> [eHdmiCEC] send message 84 FF FF 03
<   285.711> [eInit] + (30) eActionMap
<   285.712> [eInit] + (35) CI Slots
<   285.714> [eServerSocket] ERROR on bind: No such file or directory
<   285.715> [CI] scanning for common interfaces..
<   285.729> [CI] Slot: 0 setSource: A
<   285.730> [CI] Slot: 1 setSource: A
<   285.758> [CI] eDVBCIInterfaces setInputSource(0, A)
<   285.784> [CI] eDVBCIInterfaces setInputSource(1, B)
<   285.785> [CI] done, found 2 common interface slots
<   285.788> [CI] Streaming CI routing interface not advertised, assuming DVR method
<   285.789> [CI] Streaming CI finish interface not advertised, assuming "tuner" method
<   285.790> [eInit] + (35) CA handler
<   285.791> [eServerSocket] ERROR on bind: No such file or directory
<   285.791> [eInit] + (40) eServiceCenter
<   285.792> [eServiceCenter] settings instance.
<   285.792> [eInit] + (41) eServiceFactoryDVD
<   285.794> [eInit] + (41) eServiceFactoryWebTS
<   285.797> [eInit] + (41) eServiceFactoryTS
<   285.798> [eInit] + (41) eServiceFactoryHDMI
<   285.801> [eInit] + (41) eServiceFactoryM2TS
<   285.802> [eInit] + (41) eServiceFactoryFS
<   285.803> [eInit] + (41) eServiceFactoryDVB
<   285.804> [eInit] + (41) Encoders
<   285.805> [eInit] + (41) RTSP Stream server
<   285.808> [eInit] + (41) Stream server
<   285.811> [Avahi] avahi_timeout_new
<   285.817> [Avahi] avahi_timeout_free
<   285.819> [Avahi] avahi_timeout_new
<   285.824> [Avahi] avahi_timeout_free
<   285.825> [Avahi] avahi_timeout_new
<   285.830> [Avahi] avahi_timeout_free
<   285.834> [Avahi] avahi_timeout_new
<   285.840> [Avahi] avahi_timeout_free
<   285.841> [Avahi] avahi_timeout_new
<   285.847> [Avahi] avahi_timeout_free
<   285.848> [Avahi] Registered vusolo (_e2stream._tcp) on vusolo:8001
<   285.849> [eInit] reached rl 70
<   285.849> [eDVBDB] ---- opening lame channel db
<   285.850> [eDVBDB] reading services (version 4)
<   285.851> [eDVBDB] loaded 0 channels/transponders and 0 services
<   285.851> eDVBSatelliteEquipmentControl::clear()
<   285.852> [eDVBResourceManager] scanning for frontends..
<   285.854> [eDVBFrontend0] opening frontend
<   285.855> [eDVBFrontend0] opening frontend
<   285.856> [eDVBFrontend0] frontend 0 has DVB API 50a 
<   285.858> [eDVBFrontend0] close frontend
<   285.861> [eDVBAdapterLinux] get demux 0
<   285.862> [eDVBAdapterLinux] get demux 1
<   285.862> [eDVBAdapterLinux] get demux 2
<   285.863> [eDVBAdapterLinux] get demux 3
<   285.863> [eDVBAdapterLinux] get demux 4
<   285.864> [eDVBResourceManager] found 1 adapter, 1 frontends(1 sim) and 5 demux
<   285.866> [eDVBLocalTimeHandler] RTC not ready... wait for transponder time
<   285.867> [eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
<   285.869> [MAIN] Loading spinners...
<   285.885> [MAIN] found 6 spinner!
[MAIN] executing main
<   285.886> [setIoPrio] best-effort level 3 ok
<   287.363> [mytest] Open Vision version = 9.3
<   287.364> [mytest] Open Vision revision = r117
<   287.416> [eDVBFrontend] Failed to open /dev/dbox/fp0
<   287.418> [Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: No such file or directory
<   287.435> Traceback (most recent call last):
<   287.436>   File "/usr/lib/enigma2/python/mytest.py", line 21, in <module>
<   287.438>     from Components.SystemInfo import SystemInfo
<   287.439>   File "/usr/lib/enigma2/python/Components/SystemInfo.py", line 126, in <module>
<   287.441>   File "/usr/lib/enigma2/python/Tools/Multiboot.py", line 9, in getMultibootStartupDevice
<   287.442> OSError: [Errno 2] No such file or directory: '/tmp/multibootcheck'
<   287.451> [eDVBDB] ---- saving lame channel db
<   287.457> [eDVBDB] saved 0 channels and 0 services!
<   287.472> [eDVBResourceManager] release cached channel (timer timeout)
<   287.474> [Avahi] avahi_timeout_new
<   287.480> [Avahi] avahi_timeout_free
<   287.481> [Avahi] avahi_watch_free
<   287.484> [Avahi] avahi_timeout_free
<   287.489> [eInit] - (41) eServiceFactoryDVD
<   287.492> [eInit] - (41) eServiceFactoryWebTS
<   287.493> [eInit] - (41) eServiceFactoryTS
<   287.494> [eInit] - (41) eServiceFactoryHDMI
<   287.494> [eInit] - (41) eServiceFactoryM2TS
<   287.495> [eInit] - (41) eServiceFactoryFS
<   287.495> [eInit] - (41) eServiceFactoryDVB
<   287.498> [eInit] - (41) Encoders
<   287.499> [eInit] - (41) RTSP Stream server
<   287.500> [eInit] - (41) Stream server
<   287.501> [eInit] - (40) eServiceCenter
<   287.501> [eServiceCenter] clear instance
<   287.502> [eInit] - (35) CI Slots
<   287.502> [eInit] - (35) CA handler
<   287.503> [eInit] - (30) eActionMap
<   287.504> [eInit] - (22) Hdmi CEC driver
<   287.505> [eInit] - (21) input device driver
<   287.506> [eInit] - (20) DVB-CI UI
<   287.506> [eInit] - (20) UHF Modulator
<   287.507> [eInit] - (20) RC Input layer
<   287.508> [eInit] - (20) misc options
<   287.508> [eInit] - (20) AVSwitch Driver
<   287.509> [eInit] - (15) eWindowStyleManager
<   287.509> [eInit] - (10) gRC
<   287.511> [gRC] waiting for gRC thread shutdown
<   287.512> [gRC] thread has finished
<   287.512> [eInit] - (9) GFBDC
<   287.521> [eInit] - (9) gLCD
<   287.522> [eInit] - (9) Font Render Class
<   287.522> [eInit] - (8) graphics acceleration manager
<   287.523> [eInit] - (5) Tuxtxt
<   287.524> [eInit] - (1) Background File Eraser
<   287.526> [eInit] reached rl -1

**Comment by persianpros** [comment]
Ok try this one: http://www.mediafire.com/file/yevqcig4vf9q1zz/openvision-enigma2-develop-english-9.3-r117-vusolo_usb.zip/file

**Comment by ziko-ZR1** [comment]
everything is okay now

**Comment by persianpros** [comment]
Hmm then I need to change things again ...

**Comment by ziko-ZR1** [comment]
juste take your time man no need to hurry :) .

**Comment by persianpros** [comment]
Please test http://www.mediafire.com/file/s2std5ol4iyydsg/openvision-enigma2-develop-multilanguage-9.3-r117-vusolo_usb.zip/file and let me know if it's ok.

**Comment by ziko-ZR1** [comment]
this one works also

**Comment by persianpros** [comment]
Ok so I have to recude middleflash image size otherwise with the new OE update they won't boot.

Thanks for your tests :+1:
