### ISSUE TITLE
IMAGE BOOT UP | THIS PROBLEM IS STILL EXISTING

### ISSUE THREAD

**Issue by ziko-ZR1** [OpenVisionE2/enigma2-openvision#53]
Hello , tried last day update and today update but this problem is still existing , i've deleted build folder and after every update i do a full clean up 

https://github.com/OpenVisionE2/enigma2-openvision/issues/49

**Comment by persianpros** [comment]
So it won't boot again?

I think I have to remove middleflash and use smallflash for both then.

**Comment by ziko-ZR1** [comment]
yeah it stuck at boot logo and tmp folder is not created 

![Screenshot from 2020-04-16 14-21-19](https://user-images.githubusercontent.com/43075184/79467686-9317ab00-7fed-11ea-9d5c-0d54388ba67a.png)

**Comment by persianpros** [comment]
Did you add or install anything or it's a fresh install?

**Comment by ziko-ZR1** [comment]
yeah i added oscam and my channels , i've added the same as i was in old updates for exemple this is a working image 
![Screenshot from 2020-04-16 15-04-49](https://user-images.githubusercontent.com/43075184/79472967-002e3f00-7ff4-11ea-8775-05efc4213526.png)
its the same size as those i compile with new updates

**Comment by persianpros** [comment]
That's the problem, don't touch anything just compile the way we do and check if that has a problem, we're not responsible for customizations.

**Comment by ziko-ZR1** [comment]
should i open it there or u can move this issue

**Comment by persianpros** [comment]
It's ok for now, for later we do.

**Comment by ziko-ZR1** [comment]
i will compile with default and tell you the result

**Comment by ziko-ZR1** [comment]
this can be closed the image should not be above 92mb .

**Comment by ziko-ZR1** [comment]
there is one problem left , the interface eth0 i have to enable it in every boot up
